### ISSUE TITLE
repos to develop

### ISSUE THREAD

**Issue by gsi-intl** [globalmaps/projectmanagement#1]
see: [Global Map download page](https://www.iscgm.org/gmd/)
see: [Global Map Transfer Plan](https://speakerdeck.com/gsiinternational/twenty-year-journey-in-global-mapping?slide=20)
# naming convention

```
gm#{iso_3166_1_alpha_2}#{version_without_decimal_point}#{bil ? 'bil' : ''}
```
# Africa
- [x] gmcg10 https://github.com/globalmaps/gmcg10
- [x] gmcg20 https://github.com/globalmaps/gmcg20
- [x] gmcd10 https://github.com/globalmaps/gmcd10
- [x] gmet10 https://github.com/globalmaps/gmet10
- [x] gmet20 https://github.com/globalmaps/gmet20 clean
- [x] gmke10 https://github.com/globalmaps/gmke10
- [x] gmsd10 https://github.com/globalmaps/gmsd10
- [x] gmdz10 https://github.com/globalmaps/gmdz10
- [x] gmdz20 https://github.com/globalmaps/gmdz20
- [x] gmtn10 https://github.com/globalmaps/gmtn10
- [x] gmbw10 https://github.com/globalmaps/gmbw10
- [x] gmbw20 https://github.com/globalmaps/gmbw20
- [x] gmmg20 https://github.com/globalmaps/gmmg20 (raster only)
- [x] gmmu10 https://github.com/globalmaps/gmmu10
- [x] gmmz10 https://github.com/globalmaps/gmmz10
- [x] gmmz20 https://github.com/globalmaps/gmmz20
- [x] gmza10 https://github.com/globalmaps/gmza10
- [x] gmza11 https://github.com/globalmaps/gmza11 (raster only)
- [x] gmza20 https://github.com/globalmaps/gmza20 clean
- [x] gmsainthelena20 https://github.com/globalmaps/gmsainthelena20 clean
- [x] gmsz10 https://github.com/globalmaps/gmsz10 clean
- [x] gmsz20 https://github.com/globalmaps/gmsz20 clean
- [x] gmzm20 https://github.com/globalmaps/gmzm20 clean
- [x] gmzanzibar20 https://github.com/globalmaps/gmzanzibar20 clean
- [x] gmbf10 https://github.com/globalmaps/gmbf10 clean
- [x] gmbf20 https://github.com/globalmaps/gmbf20 clean
- [x] gmci20 https://github.com/globalmaps/gmci20 clean
- [x] gmgh10 https://github.com/globalmaps/gmgh10 clean
- [x] gmgw10 https://github.com/globalmaps/gmgw10 clean
- [x] gmgw20 https://github.com/globalmaps/gmgw20 clean
- [x] gmml20 https://github.com/globalmaps/gmml20 clean
- [x] gmne10 https://github.com/globalmaps/gmne10 clean
- [x] gmne20 https://github.com/globalmaps/gmne20 clean
- [x] gmsn10 https://github.com/globalmaps/gmsn10 clean
- [x] gmsn20 https://github.com/globalmaps/gmsn20 clean
- [x] gmtg20 https://github.com/globalmaps/gmtg20 clean
- [x] gmtristandacunha10 https://github.com/globalmaps/gmtristandacunha10 clean
# Asia
- [ ] gmaf20
- [ ] gmaz10
- [ ] gmaz20
- [ ] gmbh10
- [ ] gmbh20
- [ ] gmbd10
- [ ] gmbd11
- [ ] gmbd20
- [x] gmbt10 https://github.com/globalmaps/gmbt10 clean
- [x] gmbt20 https://github.com/globalmaps/gmbt20 clean
- [ ] gmbn10
- [ ] gmbn20
- [ ] gmhk10
- [ ] gmin10
- [ ] gmin20
- [ ] gmid10
- [ ] gmir10
- [ ] gmir20
- [x] gmjp at [the national site](http://www.gsi.go.jp/kankyochiri/gm_japan_e.html)
- [ ] gmjo10
- [ ] gmjo20
- [ ] gmkz10
- [x] gmkr at [the national site](http://www.ngii.go.kr/jsp/globalmap.jsp)
- [ ] gmkg10
- [ ] gmkg20
- [ ] gmla10
- [ ] gmla20
- [ ] gmlb10
- [ ] gmlb20
- [ ] gmmy10
- [ ] gmmy20
- [ ] gmmn10
- [ ] gmmn20
- [ ] gmmm10
- [ ] gmnp10
- [ ] gmnp20
- [ ] gmom10
- [ ] gmom20
- [ ] gmpk10
- [ ] gmpk20
- [ ] gmps10
- [ ] gmph10
- [ ] gmsa10
- [ ] gmsa20
- [ ] gmsg10
- [ ] gmlk10
- [ ] gmlk20
- [ ] gmsy10
- [ ] gmth10
- [ ] gmvn10
- [ ] gmvn20
# Europe
- [x] gmeu80 at [the eurogeographics site](http://www.eurogeographics.org/products-and-services/euroglobalmap)
- [x] gmal20 https://github.com/globalmaps/gmal20
- [x] gmbg10 https://github.com/globalmaps/gmbg10 clean
- [ ] gmbg20 (bil only)
- [x] gmge10 https://github.com/globalmaps/gmge10 clean
- [x] gmge20 https://github.com/globalmaps/gmge20 clean
- [x] gmmk10 https://github.com/globalmaps/gmmk10 clean
- [x] gmmk20 https://github.com/globalmaps/gmmk20 clean
- [x] gmro10 https://github.com/globalmaps/gmro10 clean
- [x] gmro20 https://github.com/globalmaps/gmro20 clean
- [x] gmrs20 https://github.com/globalmaps/gmrs20 clean
- [x] gmlv10 https://github.com/globalmaps/gmlv10 clean
- [x] gmlv20 https://github.com/globalmaps/gmlv20 clean
- [x] gmmd10 https://github.com/globalmaps/gmmd10 clean
- [x] gmxk20 https://github.com/globalmaps/gmxk20 clean
# North America
- [x] gmbz10 https://github.com/globalmaps/gmbz10 clean
- [x] gmca is at [the national site](http://geogratis.gc.ca/api/en/nrcan-rncan/ess-sst/28a7cfa1-b995-5a3c-b850-a6df2a6403b5)
- [x] gmcu10 https://github.com/globalmaps/gmcu10 clean
- [x] gmcu20 https://github.com/globalmaps/gmcu20 clean
- [x] gmdm10 https://github.com/globalmaps/gmdm10 clean
- [x] gmdm20 https://github.com/globalmaps/gmdm20 clean
- [x] gmsv20 https://github.com/globalmaps/gmsv20 clean
- [x] gmgt10 https://github.com/globalmaps/gmgt10 clean
- [x] gmhn10 https://github.com/globalmaps/gmhn10 clean
- [x] gmhn20 https://github.com/globalmaps/gmhn20 clean
- [ ] gmmx10 (email required)
- [x] gmni10 https://github.com/globalmaps/gmni10 clean
- [x] gmni20 https://github.com/globalmaps/gmni20 clean
- [x] gmpa10 https://github.com/globalmaps/gmpa10
- [x] gmlc10 https://github.com/globalmaps/gmlc10 clean
- [x] gmvc10 https://github.com/globalmaps/gmvc10 clean
- [x] gmvc20 https://github.com/globalmaps/gmvc20 clean
- [x] gmus is at [the national site](https://www.iscgm.org/gmd/download/usa.html)
# South America
- [x] gmar10  https://github.com/globalmaps/gmar10 clean
- [ ] gmbr10 (need split)
- [ ] gmbr20r (bil only)
- [x] gmcl10  https://github.com/globalmaps/gmcl10 clean
- [x] gmco10  https://github.com/globalmaps/gmco10 clean
- [x] gmuy10  https://github.com/globalmaps/gmuy10 clean
- [x] gmuy20  https://github.com/globalmaps/gmuy20 clean
# Oceania
- [x] gmau is at [the national site](https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=48006)
- [ ] gmnz10
- [ ] gmnz20
- [ ] gmpg10
- [ ] gmpg20
- [ ] gmws10
# Antarctica
- [ ] gm10aq

see: [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

**Comment by hfu** [comment]
this moved to [REPOS.md](https://github.com/globalmaps/projectmanagement/blob/master/REPOS.md)
