### ISSUE TITLE
development policy of this archives

### ISSUE THREAD

**Issue by gsi-intl** [globalmaps/projectmanagement#2]
# development policy
1. <strike>raster data and vector data are provided separately in different repositories.</strike>
2. only Shapefile data and TIFF data are to be provided. (No VPF/GML/BIL data to transfer, except in the case where there is no TIFF data provided.)
3. a file bigger than 85MB will be split by UNIX split command.
# appendix

The split command as in 3. is:

``` sh
split -b 85m #{path} #{path}.
```

**Comment by hfu** [comment]
splitting is now implemented at https://github.com/globalmaps/sardines
