### ISSUE TITLE
merge Read_me.txt into README.md

### ISSUE THREAD

**Issue by gsi-intl** [globalmaps/projectmanagement#7]
it might be good to merge Read_me.txt, which originates from the user-friendly ZIP file, into README.md, so that things will be simpler.

Maybe later.

**Comment by hfu** [comment]
Because Read_me.txt is the contents before introducing license icons, they are basically not necessary if there is README.md. So, basically we can delete Read_me.txt.

**Comment by hfu** [comment]
In addition, this logic is implemented in https://github.com/globalmaps/sardines , too.
